modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="${mod_license}"
[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory

# A file name (in the root of the mod JAR) containing a logo for display
logoFile="greatest_discount_logo.png" #optional

description='''
A simple addon to give the players the greatest discount.
The mod version refers to whatever version of ars nouveau we used during development.
The discount value is configurable, default is 40 (to be in line with the lesser (10) and greater (20) discount rings.)
'''

[[dependencies.${mod_id}]] #optional
    modId="neoforge" #mandatory
    type="required" #mandatory
    versionRange="[${neo_version},)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
modId = "ars_nouveau"
versionRange = "[1.21.1-5.4,)"
ordering = "AFTER"
side = "BOTH"